### ISSUE TITLE
Latest release breaks current-bench

### ISSUE THREAD

**Issue by ElectreAAS** [tmattio/omigrate#9]
Hi!
With the newest version of omigrate, ocurrent/current-bench fails with error below.
```
2022-10-24 15:33:18.024 UTC [93] STATEMENT:  SELECT version, dirty FROM "schema_migrations" LIMIT 1;
pipeline_1        | omigrate: internal error, uncaught exception:
pipeline_1        |           (pgx/src/types.ml.PostgreSQL_Error
pipeline_1        |             "ERROR: 42703: column \"dirty\" does not exist"
pipeline_1        |             ((code 42703) (severity ERROR) (message "column \"dirty\" does not exist")
pipeline_1        |               (custom
pipeline_1        |                 ((R errorMissingColumn) (L 3349) (F parse_relation.c) (P 17) (V ERROR)))))
```
The problem seems to come from the fact that the migrations are applied in a wrong order.
Maybe this has to do with the `LIMIT 1` which was recently added? Since `SELECT` without an explicit order will return any migration, in unspecified order.
This error is reproducible locally too

**Comment by maiste** [comment]
The issue comes from a compatibility problem between the commit after `omigrate.0.1.1` and `omigrate.0.1.1`. In the previous version, the `dirty` column was not present. With the `0.3.0` version, `omigrate` finds the `schema_migrations` database, so it doesn't try to create the table. However, the table doesn't contain a `dirty` column as it was created with `omigrate.0.1.1`. 

It requires the user to manually update the database to make `omigrate` work again. Here are three ways to do it:
1. Drop the `schema_migrations` database. `omigrate` will try to reapply all the migrations and insert the right one in the database. It will fail if the migrations are not idempotent. The code is:
```sql
DROP TABLE schema_migrations;
```
2.  Alter the schema to make it compatible with the `0.3.0` version. The code is:
```sql
ALTER TABLE schema_migrations ADD dirty boolean NOT NULL DEFAULT false;
```
3. The last option, and the best IMHO, is to insert the migration version manually. The code is:
```sql
SELECT * FROM schema_migrations ORDER BY version DESC LIMIT 1;
#  Keep the value you get here somewhere. Let's call it v.
ALTER TABLE schema_migrations ADD dirty boolean NOT NULL DEFAULT false;
TRUNCATE schema_migrations;
# Here, replace the v value with the number you get during the first step.
INSERT INTO schema_migrations VALUES (v, false); 
```
